name: Deploy to Yandex.Cloud

on:
  push:
    branches:
      - main  # замените на вашу ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build -t your-docker-hub-username/authorize:latest ./authorize
        docker build -t your-docker-hub-username/otherfunctions:latest ./otherfunctions
        docker push your-docker-hub-username/authorize:latest
        docker push your-docker-hub-username/otherfunctions:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.5.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /path/to/your/app
          docker-compose pull
          docker-compose up -d
